name: "Dependabot"
on:
  schedule:
    - cron: "0 0 * * 1" # Run once a week at midnight on Monday
jobs:
  update_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Update dependencies
        uses: dependabot/dependabot-core@latest # Use the latest version
        with:
          directory: "/" # Location of the repository
          package-manager: "bundler
