on: [ push]
jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dependabot
        uses: dependabot/dependabot-core@0.133.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: "/"
          update_schedule: "weekly"
          package_manager: "pip"
          commit_message: "Bump pip dependencies"
          commit_author_email: " allanw.mk@gmail.com"

