version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
    allow:
      - dependency-type: "all"
    ignore:
      - dependency-name: "your-ignored-dependency"
    labels:
      - "dependencies"
    reviewers:
      - "DarkStarStrix"
    assignees:
      - "DarkStarStrix"
    security-updates: true
